spring.application.name=ProyectoGaleria
# URL de conexiOn
spring.datasource.url=jdbc:postgresql://localhost:5432/galeria
spring.datasource.username=postgres
spring.datasource.password=Postgres

# ConfiguraciOn de Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
